#! /bin/csh -f
#
#   This C-shell script will attempt to build as many modules as possible.
#
#   Copyright (C) 1993,1994  Richard Gooch
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   Richard Gooch may be reached by email at  karma-request@atnf.csiro.au
#   The postal address is:
#     Richard Gooch, c/o ATNF, P. O. Box 76, Epping, N.S.W., 2121, Australia.

foreach dir (*)
    if (-d $dir) then
	if (-r $dir/.$MACHINE_OS/depend) then
	    echo $dir
	    if (-r $dir/GNUmakefile.$MACHINE_OS) then
		(cd $dir; gmake -f GNUmakefile.$MACHINE_OS $argv)
	    else
		(cd $dir; gmake $argv)
	    endif
	    echo "==============================================================================="
	    echo ""
	endif
    endif
end
