#! /bin/csh -f

# This C shell script will create the library build tree under:
# $KARMABASE/build.lib

#   Copyright (C) 1993,1994,1995  Richard Gooch
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   Richard Gooch may be reached by email at  karma-request@atnf.csiro.au
#   The postal address is:
#     Richard Gooch, c/o ATNF, P. O. Box 76, Epping, N.S.W., 2121, Australia.


# Written by		Richard Gooch	6-JAN-1993

# Last updated by	Richard Gooch	9-JUN-1995


set karmalibdir = $KARMAROOT/build/$MACHINE_OS/lib

cd $KARMAROOT
set dir = source/lib/makefiles
if ( ! -f $dir/$OS/GNUmakefile.rules ) then
    echo "Directory:  $dir/$OS/GNUmakefile.rules  does not exist"
    exit 1
endif

echo "Cleaning..."
find . \( -name '*~' -o -name '.*~' \) -print -exec rm {} \;

cd $dir

if (-r Makefile.$OS) then
    cp -p Makefile.$OS $karmalibdir/Makefile
else
    cp -p Makefile $karmalibdir
endif

cd $OS

foreach i (karma*)
    if ( ! -d $karmalibdir/$i ) then
	echo "Making directory: $karmalibdir/$i"
	mkdir $karmalibdir/$i
    endif
    if ( ! -r $karmalibdir/$i/dependfile ) then
	echo "Creating empty file: $karmalibdir/$i/dependfile"
	touch $karmalibdir/$i/dependfile
    endif
    echo $i
    if ("$OS" == "IRIX5") then
	cp $i $karmalibdir/$i/GNUmakefile
    else
	cp -p $i $karmalibdir/$i/GNUmakefile
    endif
end

exit 0
